version: '3'
services:
  apache-server:
    image: httpd
    container_name: apache-server
    restart: always
    ports:
      - "80:80"
    networks:
      - dns-network
    volumes:
      - ./html:/usr/local/apache2/htdocs
    # depends_on:
    #   - dns-server
    # links:
    #   - dns-server
  ssh-server:
    image: rastasheep/ubuntu-sshd
    container_name: ssh-server
    restart: always
    environment:
      - SSH_ROOT_PASSWORD=root
      - SSH_USER_PASSWORD=user
      - SSH_USER=user
    ports:
      - "22:22"
    networks:
      - dns-network
  dhcp-server:
    image: networkboot/dhcpd
    container_name: dhcp-server
    restart: always
    ports:
      - "67:67/udp"
    volumes:
      - ./dhcpd:/data
    network_mode: "host"
    cap_add:
      - NET_ADMIN
  bind9:
    container_name: bind-dns
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=America/New_York
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/bind:/etc/bind
      - ./dns/cache:/var/cache/bind
      - ./dns/lib/bind:/var/lib/bind
    restart: unless-stopped
networks:
  dns-network:
    driver: bridge
  